# Generated by Django 4.0.2 on 2022-03-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_rename_book_id_review_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='imdbRating',
            field=models.FloatField(default=0),
        ),
    ]
