# Generated by Django 4.0.2 on 2022-03-07 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_movies_imdbrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='movie_id',
        ),
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movies'),
        ),
    ]
